version: '3'
services:
  sneaker-db:
    image: postgres:latest
    container_name: sneaker-db
    environment:
      POSTGRES_DB: sneaker_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "8080:80"

#  sneaker-app:  
#    build:
#      context: .  
#      dockerfile: Dockerfile  
#    ports:
#      - "8481:8481"  
#    volumes:
#      - .:/app  # Mount the current directory into the container's /app directory
#    depends_on:
#      - sneaker-db