# Use the official Go image as the base image
FROM golang:1.16

# Set the working directory inside the container
WORKDIR /app

# Copy the Go app source code into the container
COPY . .

# Copy the content.json file into the container
COPY content.json .

# Install dependencies using Go modules
RUN go mod download

# Build the Go app
RUN go build -o app main.go

# Set the command to run when the container starts
CMD ["./app"]
