# Build stage
FROM golang:1.20 AS builder

ARG VERSION=dev

WORKDIR /go/src/app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app main.go

# Final stage
FROM ubuntu:20.04

# Copy the datasets.json file from your local directory to the image
COPY content.json /go/src/app/content.json

WORKDIR /go/src/app

COPY --from=builder /go/src/app/app /go/bin/app
ENV PATH="/go/bin:${PATH}"
CMD ["app"]

