# Build stage
FROM golang:1.2 AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy the Go app source code into the container
COPY go.mod go.sum ./
RUN go mod download
COPY . .
#COPY datasets.json /app/datasets.json

# Build the Go app
RUN go build -o app main.go

# Set the command to run when the container starts
CMD ["./app"]




