version: '3'
services:
  sneaker-app:  
    build:
      context: .  
      dockerfile: Dockerfile  
    ports:
      - "8481:8481"  
    volumes:
      - .:/app  # Mount the current directory into the container's /app directory
    depends_on:
      - sneaker-db  
